spring:
  application:
    name: consul-client
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: consul-client-1
#server:
#  port: 8051

management:
  endpoints:
    web:
      exposure:
        exclude: hystrix.stream
        include: refresh,health,info