spring:
  application:
    name: consul-client
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: consul-client
server:
  port: 8051

management:
  endpoints:
    web:
      exposure:
        exclude: hystrix.stream
        include: "*"